# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MESON) += meson-gxl-s905x-p212.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-sc2-s905x4-ah212.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-sc2-s905x4-gbit.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-sc2-s905x4-akari-ax810.dtb

